- name: "configuring {{ component }} server"
  hosts: all
  connection: local
  vars_files:
  - "variables-{{ environment }}.yaml"
  become: yes
  roles: 
  - "{{ component }}"

  # execute as
  # anisble-playbook main.yaml -e component=db