- name: "configure {{ component }} server"
  hosts: all
  connection: local
  vars_files:
  - variables-dev.yaml
  become: yes
  roles:
  - "{{ component }}"
  
  # execute as
  # anisble-playbook main.yaml -e component=db