- name: installing mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable MYSQL-server
  ansible.builtin.service:
    name: mysqld
    state: started # to start
    enabled: yes #to enable

#Ansible is develped in python
#now we are connecting to mysql from ansible which is develped by python
#PyMySQL is a dependency for python to connect mysql servers
- name: installing python mysql dependencies
  ansible.builtin.pip: #pip is used to install python dependencies
    name:
    - PyMySQL
    - cryptography
    executable:  pip3.9 # pip 3.11 if python version is 3.11


#check password is already setup or not
- name: checking db connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
    filter: version    #to check mysql is installed or not
  ignore_errors: yes
  register: mysql_connection_output

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{mysql_connection_output}}"

#below module is exectuted when mysql_connection_output is failed
- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}" 
  when: mysql_connection_output.failed is true


  # ansible-playbook db.yaml